name: guitarfashion
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  flutter_bloc: ^4.0.1
  cached_network_image: ^2.2.0+1
  font_awesome_flutter: ^8.5.0
  flutter_swiper: ^1.1.6
  shared_preferences: ^0.5.6+3
  path_provider: ^1.6.5
  photo_view: ^0.9.2
dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/logo.png
    - images/user.png
    - images/user-change.png
    - images/filter.png
    - images/shopping-bag.png
#      onboard
    - images/onboard/onboard_1.png
    - images/onboard/onboard_2.png
    - images/onboard/onboard_3.png
#    drawer
    - images/drawers/hot_coming.png
    - images/drawers/out-shirt.png
    - images/drawers/t-shirt.png
    - images/drawers/shirt.png
    - images/drawers/khor_kr_nat.png
    - images/drawers/khor_ka_boy.png
    - images/drawers/bag.png
    - images/drawers/belt.png
    - images/drawers/hat.png
    - images/drawers/shoe.png
    - images/drawers/share_app.png
#    tabs
    - images/tabs/shopping-bag.png
    - images/tabs/shopping-bag-focus.png
    - images/tabs/gift.png
    - images/tabs/gift-focus.png
    - images/tabs/favorite.png
    - images/tabs/favorite-focus.png
    - images/tabs/account.png
    - images/tabs/account-focus.png
#      product
    - images/product/Image7.png
#    notification
    - images/notification/noti_1.png
    - images/notification/noti_2.png
    - images/notification/noti_3.png
#      Details
    - images/details/location.png
    - images/details/contact.png
    - images/details/car.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Moullight
      fonts:
        - asset: fonts/KhmerOS_muollight.ttf
    - family: Battambang
      fonts:
        - asset: fonts/KhmerOS_battambang.ttf
    - family: Koulen
      fonts:
        - asset: fonts/KhmerOSKoulen.ttf